// Le contenu du jeu : noms francais, capitales, articles, notoriete.
//
// Natural Earth fournit la geometrie, et rien d'autre de fiable ici. Son champ
// NAME_FR est correct mais academique (« Republique populaire de Chine »), et
// ses capitales sont celles de sa table des villes : le plus gros point du
// pays. On y lit Lagos pour le Nigeria, Shanghai pour la Chine, Abidjan pour la
// Cote d'Ivoire. Tout ce fichier est donc ecrit et relu a la main.
//
//   article  sert a former des phrases justes : « Trouve la France »,
//            « Trouve le Portugal », « Trouve les Pays-Bas », « Trouve Cuba ».
//   rang     est la notoriete vue d'une ecole francaise, de 1 (a savoir) a
//            4 (pointu). C'est lui qui decoupe les niveaux de difficulte.
//   capitale a null quand la question n'a pas de reponse consensuelle : le pays
//            reste jouable a la carte, il sort seulement du mode capitales.

export const PAYS = {

    // ---------- Europe ----------
    FRA: { nom: 'France', article: 'la', capitale: 'Paris', rang: 1 },
    DEU: { nom: 'Allemagne', article: "l'", capitale: 'Berlin', rang: 1 },
    ESP: { nom: 'Espagne', article: "l'", capitale: 'Madrid', rang: 1 },
    ITA: { nom: 'Italie', article: "l'", capitale: 'Rome', rang: 1 },
    PRT: { nom: 'Portugal', article: 'le', capitale: 'Lisbonne', rang: 1 },
    GBR: { nom: 'Royaume-Uni', article: 'le', capitale: 'Londres', rang: 1, alias: ['Grande-Bretagne'] },
    IRL: { nom: 'Irlande', article: "l'", capitale: 'Dublin', rang: 1 },
    BEL: { nom: 'Belgique', article: 'la', capitale: 'Bruxelles', rang: 1 },
    NLD: { nom: 'Pays-Bas', article: 'les', capitale: 'Amsterdam', rang: 1 },
    LUX: { nom: 'Luxembourg', article: 'le', capitale: 'Luxembourg', rang: 1 },
    CHE: { nom: 'Suisse', article: 'la', capitale: 'Berne', rang: 1 },
    AUT: { nom: 'Autriche', article: "l'", capitale: 'Vienne', rang: 1 },
    POL: { nom: 'Pologne', article: 'la', capitale: 'Varsovie', rang: 1 },
    CZE: { nom: 'Tchéquie', article: 'la', capitale: 'Prague', rang: 1, alias: ['République tchèque'] },
    DNK: { nom: 'Danemark', article: 'le', capitale: 'Copenhague', rang: 1 },
    NOR: { nom: 'Norvège', article: 'la', capitale: 'Oslo', rang: 1 },
    SWE: { nom: 'Suède', article: 'la', capitale: 'Stockholm', rang: 1 },
    FIN: { nom: 'Finlande', article: 'la', capitale: 'Helsinki', rang: 1 },
    ISL: { nom: 'Islande', article: "l'", capitale: 'Reykjavik', rang: 1 },
    GRC: { nom: 'Grèce', article: 'la', capitale: 'Athènes', rang: 1 },
    RUS: { nom: 'Russie', article: 'la', capitale: 'Moscou', rang: 1 },
    UKR: { nom: 'Ukraine', article: "l'", capitale: 'Kiev', rang: 1 },
    HRV: { nom: 'Croatie', article: 'la', capitale: 'Zagreb', rang: 1 },
    HUN: { nom: 'Hongrie', article: 'la', capitale: 'Budapest', rang: 2 },
    ROU: { nom: 'Roumanie', article: 'la', capitale: 'Bucarest', rang: 2 },
    BGR: { nom: 'Bulgarie', article: 'la', capitale: 'Sofia', rang: 2 },
    SRB: { nom: 'Serbie', article: 'la', capitale: 'Belgrade', rang: 2 },
    SVK: { nom: 'Slovaquie', article: 'la', capitale: 'Bratislava', rang: 2 },
    SVN: { nom: 'Slovénie', article: 'la', capitale: 'Ljubljana', rang: 2 },
    BIH: { nom: 'Bosnie-Herzégovine', article: 'la', capitale: 'Sarajevo', rang: 2 },
    ALB: { nom: 'Albanie', article: "l'", capitale: 'Tirana', rang: 2 },
    BLR: { nom: 'Biélorussie', article: 'la', capitale: 'Minsk', rang: 2 },
    MCO: { nom: 'Monaco', article: '', capitale: 'Monaco', rang: 2 },
    EST: { nom: 'Estonie', article: "l'", capitale: 'Tallinn', rang: 3 },
    LVA: { nom: 'Lettonie', article: 'la', capitale: 'Riga', rang: 3 },
    LTU: { nom: 'Lituanie', article: 'la', capitale: 'Vilnius', rang: 3 },
    MDA: { nom: 'Moldavie', article: 'la', capitale: 'Chisinau', rang: 3 },
    MKD: { nom: 'Macédoine du Nord', article: 'la', capitale: 'Skopje', rang: 3, alias: ['Macédoine'] },
    MNE: { nom: 'Monténégro', article: 'le', capitale: 'Podgorica', rang: 3 },
    XKX: { nom: 'Kosovo', article: 'le', capitale: 'Pristina', rang: 3 },
    MLT: { nom: 'Malte', article: '', capitale: 'La Valette', rang: 3 },
    AND: { nom: 'Andorre', article: '', capitale: 'Andorre-la-Vieille', rang: 3 },
    VAT: { nom: 'Vatican', article: 'le', capitale: 'Vatican', rang: 3, alias: ['Saint-Siège'] },
    SMR: { nom: 'Saint-Marin', article: '', capitale: 'Saint-Marin', rang: 4 },
    LIE: { nom: 'Liechtenstein', article: 'le', capitale: 'Vaduz', rang: 4 },

    // ---------- Asie ----------
    CHN: { nom: 'Chine', article: 'la', capitale: 'Pékin', rang: 1 },
    IND: { nom: 'Inde', article: "l'", capitale: 'New Delhi', rang: 1 },
    JPN: { nom: 'Japon', article: 'le', capitale: 'Tokyo', rang: 1 },
    IDN: { nom: 'Indonésie', article: "l'", capitale: 'Jakarta', rang: 1 },
    PAK: { nom: 'Pakistan', article: 'le', capitale: 'Islamabad', rang: 1 },
    TUR: { nom: 'Turquie', article: 'la', capitale: 'Ankara', rang: 1 },
    IRN: { nom: 'Iran', article: "l'", capitale: 'Téhéran', rang: 1 },
    SAU: { nom: 'Arabie saoudite', article: "l'", capitale: 'Riyad', rang: 1 },
    ISR: { nom: 'Israël', article: '', capitale: null, rang: 1 },
    THA: { nom: 'Thaïlande', article: 'la', capitale: 'Bangkok', rang: 1 },
    VNM: { nom: 'Viêt Nam', article: 'le', capitale: 'Hanoï', rang: 1, alias: ['Vietnam'] },
    PHL: { nom: 'Philippines', article: 'les', capitale: 'Manille', rang: 1 },
    KOR: { nom: 'Corée du Sud', article: 'la', capitale: 'Séoul', rang: 1 },
    PRK: { nom: 'Corée du Nord', article: 'la', capitale: 'Pyongyang', rang: 1 },
    AFG: { nom: 'Afghanistan', article: "l'", capitale: 'Kaboul', rang: 2 },
    IRQ: { nom: 'Irak', article: "l'", capitale: 'Bagdad', rang: 2 },
    SYR: { nom: 'Syrie', article: 'la', capitale: 'Damas', rang: 2 },
    LBN: { nom: 'Liban', article: 'le', capitale: 'Beyrouth', rang: 2 },
    BGD: { nom: 'Bangladesh', article: 'le', capitale: 'Dacca', rang: 2 },
    NPL: { nom: 'Népal', article: 'le', capitale: 'Katmandou', rang: 2 },
    MYS: { nom: 'Malaisie', article: 'la', capitale: 'Kuala Lumpur', rang: 2 },
    SGP: { nom: 'Singapour', article: '', capitale: 'Singapour', rang: 2 },
    KHM: { nom: 'Cambodge', article: 'le', capitale: 'Phnom Penh', rang: 2 },
    MNG: { nom: 'Mongolie', article: 'la', capitale: 'Oulan-Bator', rang: 2 },
    KAZ: { nom: 'Kazakhstan', article: 'le', capitale: 'Astana', rang: 2 },
    ARE: { nom: 'Émirats arabes unis', article: 'les', capitale: 'Abou Dabi', rang: 2 },
    QAT: { nom: 'Qatar', article: 'le', capitale: 'Doha', rang: 2 },
    TWN: { nom: 'Taïwan', article: '', capitale: 'Taipei', rang: 2 },
    PSE: { nom: 'Palestine', article: 'la', capitale: null, rang: 2, alias: ['Territoires palestiniens'] },
    LKA: { nom: 'Sri Lanka', article: '', capitale: 'Colombo', rang: 3 },
    MMR: { nom: 'Birmanie', article: 'la', capitale: 'Naypyidaw', rang: 3, alias: ['Myanmar'] },
    LAO: { nom: 'Laos', article: 'le', capitale: 'Vientiane', rang: 3 },
    YEM: { nom: 'Yémen', article: 'le', capitale: 'Sanaa', rang: 3 },
    OMN: { nom: 'Oman', article: '', capitale: 'Mascate', rang: 3 },
    JOR: { nom: 'Jordanie', article: 'la', capitale: 'Amman', rang: 3 },
    KWT: { nom: 'Koweït', article: 'le', capitale: 'Koweït', rang: 3 },
    GEO: { nom: 'Géorgie', article: 'la', capitale: 'Tbilissi', rang: 3 },
    ARM: { nom: 'Arménie', article: "l'", capitale: 'Erevan', rang: 3 },
    AZE: { nom: 'Azerbaïdjan', article: "l'", capitale: 'Bakou', rang: 3 },
    UZB: { nom: 'Ouzbékistan', article: "l'", capitale: 'Tachkent', rang: 3 },
    CYP: { nom: 'Chypre', article: '', capitale: 'Nicosie', rang: 3 },
    BHR: { nom: 'Bahreïn', article: '', capitale: 'Manama', rang: 4 },
    BTN: { nom: 'Bhoutan', article: 'le', capitale: 'Thimphou', rang: 4 },
    BRN: { nom: 'Brunei', article: 'le', capitale: 'Bandar Seri Begawan', rang: 4 },
    MDV: { nom: 'Maldives', article: 'les', capitale: 'Malé', rang: 4 },
    TLS: { nom: 'Timor oriental', article: 'le', capitale: 'Dili', rang: 4, alias: ['Timor-Leste'] },
    TJK: { nom: 'Tadjikistan', article: 'le', capitale: 'Douchanbé', rang: 4 },
    TKM: { nom: 'Turkménistan', article: 'le', capitale: 'Achgabat', rang: 4 },
    KGZ: { nom: 'Kirghizistan', article: 'le', capitale: 'Bichkek', rang: 4 },

    // ---------- Afrique ----------
    MAR: { nom: 'Maroc', article: 'le', capitale: 'Rabat', rang: 1 },
    DZA: { nom: 'Algérie', article: "l'", capitale: 'Alger', rang: 1 },
    TUN: { nom: 'Tunisie', article: 'la', capitale: 'Tunis', rang: 1 },
    EGY: { nom: 'Égypte', article: "l'", capitale: 'Le Caire', rang: 1 },
    SEN: { nom: 'Sénégal', article: 'le', capitale: 'Dakar', rang: 1 },
    MLI: { nom: 'Mali', article: 'le', capitale: 'Bamako', rang: 1 },
    CIV: { nom: "Côte d'Ivoire", article: 'la', capitale: 'Yamoussoukro', rang: 1 },
    NGA: { nom: 'Nigeria', article: 'le', capitale: 'Abuja', rang: 1 },
    KEN: { nom: 'Kenya', article: 'le', capitale: 'Nairobi', rang: 1 },
    ZAF: { nom: 'Afrique du Sud', article: "l'", capitale: 'Pretoria', rang: 1 },
    MDG: { nom: 'Madagascar', article: '', capitale: 'Antananarivo', rang: 2 },
    ETH: { nom: 'Éthiopie', article: "l'", capitale: 'Addis-Abeba', rang: 2 },
    LBY: { nom: 'Libye', article: 'la', capitale: 'Tripoli', rang: 2 },
    SDN: { nom: 'Soudan', article: 'le', capitale: 'Khartoum', rang: 2 },
    TZA: { nom: 'Tanzanie', article: 'la', capitale: 'Dodoma', rang: 2 },
    GHA: { nom: 'Ghana', article: 'le', capitale: 'Accra', rang: 2 },
    CMR: { nom: 'Cameroun', article: 'le', capitale: 'Yaoundé', rang: 2 },
    NER: { nom: 'Niger', article: 'le', capitale: 'Niamey', rang: 2 },
    TCD: { nom: 'Tchad', article: 'le', capitale: "N'Djamena", rang: 2 },
    BFA: { nom: 'Burkina Faso', article: 'le', capitale: 'Ouagadougou', rang: 2 },
    COD: { nom: 'République démocratique du Congo', article: 'la', capitale: 'Kinshasa', rang: 2, alias: ['RDC', 'Congo-Kinshasa', 'Zaïre'] },
    AGO: { nom: 'Angola', article: "l'", capitale: 'Luanda', rang: 3 },
    MOZ: { nom: 'Mozambique', article: 'le', capitale: 'Maputo', rang: 3 },
    ZWE: { nom: 'Zimbabwe', article: 'le', capitale: 'Harare', rang: 3 },
    ZMB: { nom: 'Zambie', article: 'la', capitale: 'Lusaka', rang: 3 },
    NAM: { nom: 'Namibie', article: 'la', capitale: 'Windhoek', rang: 3 },
    BWA: { nom: 'Botswana', article: 'le', capitale: 'Gaborone', rang: 3 },
    UGA: { nom: 'Ouganda', article: "l'", capitale: 'Kampala', rang: 3 },
    RWA: { nom: 'Rwanda', article: 'le', capitale: 'Kigali', rang: 3 },
    SOM: { nom: 'Somalie', article: 'la', capitale: 'Mogadiscio', rang: 3 },
    MRT: { nom: 'Mauritanie', article: 'la', capitale: 'Nouakchott', rang: 3 },
    GIN: { nom: 'Guinée', article: 'la', capitale: 'Conakry', rang: 3 },
    BEN: { nom: 'Bénin', article: 'le', capitale: 'Porto-Novo', rang: 3 },
    TGO: { nom: 'Togo', article: 'le', capitale: 'Lomé', rang: 3 },
    GAB: { nom: 'Gabon', article: 'le', capitale: 'Libreville', rang: 3 },
    COG: { nom: 'République du Congo', article: 'la', capitale: 'Brazzaville', rang: 3, alias: ['Congo-Brazzaville'] },
    CAF: { nom: 'République centrafricaine', article: 'la', capitale: 'Bangui', rang: 3 },
    SSD: { nom: 'Soudan du Sud', article: 'le', capitale: 'Djouba', rang: 3 },
    ERI: { nom: 'Érythrée', article: "l'", capitale: 'Asmara', rang: 3 },
    LBR: { nom: 'Liberia', article: 'le', capitale: 'Monrovia', rang: 3 },
    SLE: { nom: 'Sierra Leone', article: 'la', capitale: 'Freetown', rang: 3 },
    MUS: { nom: 'Maurice', article: '', capitale: 'Port-Louis', rang: 3, alias: ['Île Maurice'] },
    MWI: { nom: 'Malawi', article: 'le', capitale: 'Lilongwe', rang: 4 },
    BDI: { nom: 'Burundi', article: 'le', capitale: 'Gitega', rang: 4 },
    GMB: { nom: 'Gambie', article: 'la', capitale: 'Banjul', rang: 4 },
    GNB: { nom: 'Guinée-Bissau', article: 'la', capitale: 'Bissau', rang: 4 },
    GNQ: { nom: 'Guinée équatoriale', article: 'la', capitale: 'Malabo', rang: 4 },
    DJI: { nom: 'Djibouti', article: '', capitale: 'Djibouti', rang: 4 },
    LSO: { nom: 'Lesotho', article: 'le', capitale: 'Maseru', rang: 4 },
    SWZ: { nom: 'Eswatini', article: "l'", capitale: 'Mbabane', rang: 4, alias: ['Swaziland'] },
    CPV: { nom: 'Cap-Vert', article: 'le', capitale: 'Praia', rang: 4 },
    COM: { nom: 'Comores', article: 'les', capitale: 'Moroni', rang: 4 },
    STP: { nom: 'Sao Tomé-et-Principe', article: '', capitale: 'São Tomé', rang: 4 },
    SYC: { nom: 'Seychelles', article: 'les', capitale: 'Victoria', rang: 4 },

    // ---------- Amériques ----------
    USA: { nom: 'États-Unis', article: 'les', capitale: 'Washington', rang: 1, alias: ["États-Unis d'Amérique", 'USA'] },
    CAN: { nom: 'Canada', article: 'le', capitale: 'Ottawa', rang: 1 },
    MEX: { nom: 'Mexique', article: 'le', capitale: 'Mexico', rang: 1 },
    BRA: { nom: 'Brésil', article: 'le', capitale: 'Brasilia', rang: 1 },
    ARG: { nom: 'Argentine', article: "l'", capitale: 'Buenos Aires', rang: 1 },
    CHL: { nom: 'Chili', article: 'le', capitale: 'Santiago', rang: 1 },
    PER: { nom: 'Pérou', article: 'le', capitale: 'Lima', rang: 1 },
    CUB: { nom: 'Cuba', article: '', capitale: 'La Havane', rang: 1 },
    COL: { nom: 'Colombie', article: 'la', capitale: 'Bogota', rang: 2 },
    VEN: { nom: 'Venezuela', article: 'le', capitale: 'Caracas', rang: 2 },
    BOL: { nom: 'Bolivie', article: 'la', capitale: 'Sucre', rang: 2 },
    ECU: { nom: 'Équateur', article: "l'", capitale: 'Quito', rang: 2 },
    URY: { nom: 'Uruguay', article: "l'", capitale: 'Montevideo', rang: 2 },
    PRY: { nom: 'Paraguay', article: 'le', capitale: 'Asuncion', rang: 2 },
    HTI: { nom: 'Haïti', article: '', capitale: 'Port-au-Prince', rang: 2 },
    PAN: { nom: 'Panama', article: 'le', capitale: 'Panama', rang: 2 },
    JAM: { nom: 'Jamaïque', article: 'la', capitale: 'Kingston', rang: 3 },
    DOM: { nom: 'République dominicaine', article: 'la', capitale: 'Saint-Domingue', rang: 3 },
    GTM: { nom: 'Guatemala', article: 'le', capitale: 'Guatemala', rang: 3 },
    HND: { nom: 'Honduras', article: 'le', capitale: 'Tegucigalpa', rang: 3 },
    NIC: { nom: 'Nicaragua', article: 'le', capitale: 'Managua', rang: 3 },
    CRI: { nom: 'Costa Rica', article: 'le', capitale: 'San José', rang: 3 },
    SLV: { nom: 'Salvador', article: 'le', capitale: 'San Salvador', rang: 3, alias: ['El Salvador'] },
    GUY: { nom: 'Guyana', article: 'le', capitale: 'Georgetown', rang: 4 },
    SUR: { nom: 'Suriname', article: 'le', capitale: 'Paramaribo', rang: 4 },
    BLZ: { nom: 'Belize', article: 'le', capitale: 'Belmopan', rang: 4 },
    BHS: { nom: 'Bahamas', article: 'les', capitale: 'Nassau', rang: 4 },
    TTO: { nom: 'Trinité-et-Tobago', article: '', capitale: "Port-d'Espagne", rang: 4 },
    BRB: { nom: 'Barbade', article: 'la', capitale: 'Bridgetown', rang: 4 },
    LCA: { nom: 'Sainte-Lucie', article: '', capitale: 'Castries', rang: 4 },
    GRD: { nom: 'Grenade', article: 'la', capitale: 'Saint-Georges', rang: 4 },
    VCT: { nom: 'Saint-Vincent-et-les-Grenadines', article: '', capitale: 'Kingstown', rang: 4 },
    ATG: { nom: 'Antigua-et-Barbuda', article: '', capitale: "Saint John's", rang: 4 },
    DMA: { nom: 'Dominique', article: 'la', capitale: 'Roseau', rang: 4 },
    KNA: { nom: 'Saint-Christophe-et-Niévès', article: '', capitale: 'Basseterre', rang: 4 },

    // ---------- Oceanie ----------
    AUS: { nom: 'Australie', article: "l'", capitale: 'Canberra', rang: 1 },
    NZL: { nom: 'Nouvelle-Zélande', article: 'la', capitale: 'Wellington', rang: 1 },
    PNG: { nom: 'Papouasie-Nouvelle-Guinée', article: 'la', capitale: 'Port Moresby', rang: 2 },
    FJI: { nom: 'Fidji', article: 'les', capitale: 'Suva', rang: 3 },
    SLB: { nom: 'Îles Salomon', article: 'les', capitale: 'Honiara', rang: 4 },
    VUT: { nom: 'Vanuatu', article: 'le', capitale: 'Port-Vila', rang: 4 },
    WSM: { nom: 'Samoa', article: 'les', capitale: 'Apia', rang: 4 },
    TON: { nom: 'Tonga', article: 'les', capitale: "Nuku'alofa", rang: 4 },
    KIR: { nom: 'Kiribati', article: '', capitale: 'Tarawa', rang: 4 },
    FSM: { nom: 'Micronésie', article: 'la', capitale: 'Palikir', rang: 4 },
    MHL: { nom: 'Îles Marshall', article: 'les', capitale: 'Majuro', rang: 4 },
    PLW: { nom: 'Palaos', article: 'les', capitale: 'Ngerulmud', rang: 4 },
    NRU: { nom: 'Nauru', article: '', capitale: 'Yaren', rang: 4 },
    TUV: { nom: 'Tuvalu', article: '', capitale: 'Funafuti', rang: 4 }
};

// Les reponses fausses assez frequentes pour meriter mieux qu'un « non ».
// Un enfant qui ecrit « Angleterre » sur le Royaume-Uni ne s'est pas trompe de
// pays : il lui manque une precision, et c'est le moment de la lui donner.
export const PIEGES = [
    { saisie: 'angleterre', pour: ['GBR'], message: "L’Angleterre n’est qu’une partie du Royaume-Uni." },
    { saisie: 'ecosse', pour: ['GBR'], message: "L’Écosse fait partie du Royaume-Uni." },
    { saisie: 'pays de galles', pour: ['GBR'], message: "Le pays de Galles fait partie du Royaume-Uni." },
    { saisie: 'hollande', pour: ['NLD'], message: "La Hollande n’est qu’une région des Pays-Bas." },
    { saisie: 'congo', pour: ['COD', 'COG'], message: "Il y en a deux : la République du Congo et la République démocratique du Congo." },
    { saisie: 'coree', pour: ['KOR', 'PRK'], message: "Laquelle ? Il y a la Corée du Nord et la Corée du Sud." },
    { saisie: 'amerique', pour: ['USA'], message: "L’Amérique est un continent — le pays s’appelle les États-Unis." },
    { saisie: 'hindou', pour: ['IND'], message: "Le pays s’écrit « Inde »." },
    { saisie: 'perse', pour: ['IRN'], message: "La Perse s’appelle l’Iran depuis 1935." },
    { saisie: 'birmanie', pour: ['MMR'], message: "" },
    { saisie: 'republique tcheque', pour: ['CZE'], message: "" }
];

export const CONTINENTS = {
    Europe: 'Europe', Asia: 'Asie', Africa: 'Afrique',
    'North America': 'Amérique du Nord', 'South America': 'Amérique du Sud',
    Oceania: 'Océanie', 'Seven seas (open ocean)': 'Océans', Antarctica: 'Antarctique'
};
